import bcrypt from 'bcryptjs';

const data = {
    users: [
        {
            name: 'Chanchal',
            email: 'ptchanchal@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: true,
        },
        {
            name: 'John',
            email: 'user@gmail.com',
            password: bcrypt.hashSync('1234', 8),
            isAdmin: false,
        },
    ],
    products: [
        {
            name: 'Red Wine',
            category: 'Red',
            image: '/images/laptop.jpg',
            price: 120,
            countInStock: 10,
            brand: 'abc',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'White Wine',
            category: 'Red',
            image: '/images/ipad.jpg',
            price: 456,
            countInStock: 20,
            brand: 'xyz',
            rating: 4.0,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            name: 'Blue Wine',
            category: 'white',
            image: '/images/mobile.jpg',
            price: 124,
            countInStock: 0,
            brand: 'rty',
            rating: 3.5,
            numReviews: 10,
            description: 'medium quality product',
        },
        {
            name: 'black Wine',
            category: 'Red',
            image: '/images/headphone.jpg',
            price: 400,
            countInStock: 15,
            brand: 'wdf',
            rating: 5,
            numReviews: 5,
            description: 'normal quality product',
        },
        {
            name: 'green Wine',
            category: 'white',
            image: '/images/camera.jpg',
            price: 600,
            countInStock: 55,
            brand: 'abc',
            rating: 3,
            numReviews: 7,
            description: 'low quality product',
        },
        {
            name: 'yellow Wine',
            category: 'Red',
            image: '/images/wine6.jpg',
            price: 875,
            countInStock: 12,
            brand: 'qas',
            rating: 5,
            numReviews: 13,
            description: 'high quality product',
        },
    ],
};
export default data;